version: '3.8'

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  ollama-webui:
    depends_on: 
      - ollama
    image: ghcr.io/ollama-webui/ollama-webui:main
    ports:
      - "2029:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ollama-webui:/app/backend/data
    container_name: ollama-webui
    restart: always

volumes:
  ollama:
  ollama-webui:
